sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RckO+7IEDElmVorA3njMqei6idH81RiIPN280aYxjR/ZVXFYnBPr1LWBCqgif2vkXEm/GEW6fDEZIRx3hY4OVlRjXF9FHXbVNcYqvc8kwuQ4ofgfE1XCVi+WtuNEDeMTM3JiMAWUARLQqXB2L6mFVUls8K+K349QfM2S16BeMRMoiuVLE/84qeWte+OtMe6Wa+HwSSrR3mX+n11+pE+vXjPI3xtpzGuAcfoOehpZ8gQLFYuXVRqJAxlGuI8zj5tyhI5CV3thLAyfiHkUgQwgz/opsvJYwWF+o48UqZFsjaosdztrOMgzp/LPZJEV9ixxHDimkQ3eGPTphtma8rpMXqIaYZnyrhBLilZqbpnGxegaRBDdR8v5FhUrqEiykouWRcKT+lhbegP23PH5h9bbUk+YE2hunEbm5y6n7Gfn0M4I+Ev9+0y6F2m9OIBNYwYUbYwj10JfVLHhwCjw4mBRD6BH+rjEZR15/xyfCL/d56JrTCeQtWUNffugUf3EdKa89WKpHT6q1lUFwK4Jc4jzE8+yS0D8IkHG9zPDFAuwB5BSOdI4h+zFVQAXoHEjnMu14PgniohdlO1ynOvfuSjMaDsCr31oOuyt9jCtXRFLqA0wz4KxfR5U6lX+OKlHY++p8xz1LBuV+12OP9WA/vieZu36iGPQz1hbTUaVgXMIBiw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/History-of-the-United-Netherlands-1588b_4856
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy